mv ../original_data/img/1/* ../data/train/img0/img
mv ../original_data/img/2/* ../data/train/img0/img
mv ../original_data/img/3/* ../data/train/img0/img
mv ../original_data/img/4/* ../data/train/img0/img
mv ../original_data/img/5/* ../data/train/img0/img
mv ../original_data/img/6/* ../data/train/img0/img
mv ../original_data/img/7/* ../data/train/img0/img
mv ../original_data/img/8/* ../data/train/img0/img
mv ../original_data/img/9/* ../data/train/img0/img
mv ../original_data/img/10/* ../data/train/img0/img
mv ../original_data/img/16/* ../data/train/img0/img
mv ../original_data/img/17/* ../data/train/img0/img
mv ../original_data/img/18/* ../data/train/img0/img
mv ../original_data/img/19/* ../data/train/img0/img
mv ../original_data/img/20/* ../data/train/img0/img

mv ../original_data/label/1/* ../data/train/mask0/mask
mv ../original_data/label/2/* ../data/train/mask0/mask
mv ../original_data/label/3/* ../data/train/mask0/mask
mv ../original_data/label/4/* ../data/train/mask0/mask
mv ../original_data/label/5/* ../data/train/mask0/mask
mv ../original_data/label/6/* ../data/train/mask0/mask
mv ../original_data/label/7/* ../data/train/mask0/mask
mv ../original_data/label/8/* ../data/train/mask0/mask
mv ../original_data/label/9/* ../data/train/mask0/mask
mv ../original_data/label/10/* ../data/train/mask0/mask
mv ../original_data/label/16/* ../data/train/mask0/mask
mv ../original_data/label/17/* ../data/train/mask0/mask
mv ../original_data/label/18/* ../data/train/mask0/mask
mv ../original_data/label/19/* ../data/train/mask0/mask
mv ../original_data/label/20/* ../data/train/mask0/mask